import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "../components/Sidebar";
import AuthProvider from "../components/AuthProvider";
import { getServerSession } from "next-auth";
import Login from "@/components/Login";
import ClientProvider from "@/components/ClientProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Chatgpt clone",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className=" ">
        <AuthProvider session={session}>
          {!session ? (
            <Login />
          ) : (
            <div className="flex">
              <div className="bg-[#202123] max-w-xs h-screen overflow-y-auto md:min-w-[20rem]">
                <Sidebar />
              </div>
              {/* ClientProvider - notification */}
              <ClientProvider />
              <div className="flex-1 bg-[#343541]">{children}</div>
            </div>
          )}
        </AuthProvider>
      </body>
    </html>
  );
}
